#!/usr/bin/python
import os

os.system("cd ./output/")
file_names = sorted(os.listdir("."))
os.system("pdfjoin %s --outfile ../all_countries.pdf" % (" ".join(file_names)))
os.system("cd ..")
os.system("pdf90 all_countries.pdf")